# Generated by Django 5.1.7 on 2025-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('last_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table_comment': 'Project Details',
            },
        ),
    ]
