# Generated by Django 5.1.7 on 2025-03-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_details',
            new_name='task_description',
        ),
    ]
