# Generated by Django 5.1.7 on 2025-03-27 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_rename_task_details_task_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('work_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_log_time', models.IntegerField()),
                ('work_log_description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Work Log Details',
            },
        ),
    ]
