# Generated by Django 5.1.7 on 2025-04-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_rename_report_content_taskreport_report_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskreport',
            old_name='report_File',
            new_name='report_file',
        ),
    ]
